[package]
name = "s_serca"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
reqwest = "0.12.15"
scraper = "0.23.1"
serca = { path = "./serca/" }
tokio = { version = "1", features = ["full"] }
url = "2.5.4"
