[package]
name = "serca"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
actix = "0.13.5"
anyhow = "1.0.97"
futures = "0.3.31"
reqwest = "0.12.15"
scraper = "0.23.1"
url = "2.5.4"
fantoccini = "0.21.5"
sysinfo = "0.34.2"
