[package]
name = "elvira"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
http = "1.3.1"
log = "0.4.26"
reqwest = "0.12.15"
robots_txt = "0.7.0"
scraper = "0.23.1"
tokio = { version = "1.44.1", features = ["full"] }
url = "2.5.4"
